# Generated by Django 4.2.1 on 2023-05-04 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_associationcommentaire_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationcommentaire',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.note'),
        ),
    ]
